version: '3.9'
services:
  mariadb:
    build:
      context: "./requirements/mariadb"
      dockerfile: Dockerfile
      args:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/home/rgorki/Projetos-C-Cpp/container/inception/srcs/requirements/mariadb/tools
    expose:
      - 3306
    init: true
volumes:
  db_data:

